export interface Konu {
  id: string
  baslik: string
  emoji: string
  sure: string
  seviye: 'Temel' | 'Orta' | 'İleri' | 'Basic' | 'Medium' | 'Advanced'
  ozet: string
  maddeler: string[]
}

export interface Kategori {
  id: string
  baslik: string
  emoji: string
  renk: string
  konular: Konu[]
}

const TR_KATEGORILER: Kategori[] = [
  {
    id: 'zihniyet',
    baslik: 'Zihniyet & Temel',
    emoji: '🧠',
    renk: 'bg-[#EEF2FF] dark:bg-[#1e1b4b] text-[#3730A3] dark:text-[#a5b4fc] border-[#E0E7FF] dark:border-[#312e8130]',
    konular: [
      {
        id: 'z1',
        baslik: 'Network Marketing Nedir?',
        emoji: '🌐',
        sure: '5 dk',
        seviye: 'Temel',
        ozet: 'İşin gerçek tanımı, efsanelerden arındırılmış sade anlatım.',
        maddeler: [
          'NM, doğrudan satış ve kişisel tavsiye ekonomisinin birleşimidir.',
          'Şirket, reklam bütçesini distribütörlere komisyon olarak öder.',
          'Kazanç iki kaynaktan gelir: kendi satışın ve ekibinin satışı.',
          'Yasal NM\'de ürün gerçek, tüketim sürekli, büyüme sürdürülebilir.',
          'Piramit sistemiyle farkı: NM\'de çıkılan basamağı geride bırakabilirsin.',
        ],
      },
      {
        id: 'z2',
        baslik: 'Niçin Çoğu İnsan Bırakıyor?',
        emoji: '🚶',
        sure: '4 dk',
        seviye: 'Temel',
        ozet: 'İstatistiklerin arkasındaki gerçek ve onlardan sıyrılma yolu.',
        maddeler: [
          'Çoğu insan ilk 90 günde bırakır — yanlış beklenti nedeniyle.',
          'NM bir maraton, sprint değil; yavaş ama güçlü büyüme gerektirir.',
          'Sosyal baskı ve ilk reddedilmeler en yaygın bırakma nedenidir.',
          'Sürekli kalan %20, toplamın %80\'ini kazanır — bu her alanda böyle.',
          'Çözüm: net bir "neden" bulmak ve mentorla çalışmak.',
        ],
      },
      {
        id: 'z3',
        baslik: 'Büyüme Zihniyeti',
        emoji: '🌱',
        sure: '6 dk',
        seviye: 'Temel',
        ozet: 'Sabit zihniyet tuzağından çıkış ve gelişime açık olmanın pratiği.',
        maddeler: [
          '"Doğuştan satıcı değilim" sabit zihniyet tuzağıdır.',
          'Beceriler öğrenilir — iletişim, takip, sunum, liderlik.',
          'Her reddedilme, evet\'e bir adım daha yaklaşmak demektir.',
          'Geri bildirimi kişisel almamak: "hayır" sana değil, zamana söyleniyor.',
          'Kitap, podcast ve gözlemin günlük zihinsel "egzersizin" olsun.',
        ],
      },
      {
        id: 'z4',
        baslik: 'Reddedilmenin Sırrı: "Hayır" Ne Demek?',
        emoji: '🛡️',
        sure: '5 dk',
        seviye: 'Temel',
        ozet: 'Network marketingde reddedilme korkusu en büyük engeldir — "hayır"ı yeniden çerçevele.',
        maddeler: [
          '"Hayır" genellikle zamana, yorgunluğa veya netlik eksikliğine söyleniyor — sana değil.',
          '"Hayır çeşitleri": "şimdi değil" → sonra dön; "bu yolla değil" → yaklaşımı değiştir; "asla" → ilişkiyi koru.',
          'Bu hafta 5 kişiyle konuş; "hayır" alsan bile kapıyı açık bırak.',
          '"Ne zaman tekrar yazabilirim?" sorusunu sor — baskı değil, netlik.',
          'Hareketsiz kalmak, reddedilmekten daha büyük risktir.',
        ],
      },
      {
        id: 'z5',
        baslik: 'Motivasyon Düştüğünde Ne Yaparsın?',
        emoji: '🔋',
        sure: '7 dk',
        seviye: 'Temel',
        ozet: 'Motivasyon dalgalanır — bu normaldir. 7 pratik araç ve SWSWSWN çerçevesiyle ritme geri dön.',
        maddeler: [
          'Motivasyon düşüşü enerji değil, netlik sorunudur: "neden yaptığımı unuttum" demektir.',
          '7 araç: Neden listeni yenile → Küçük başarı yarat → Mentoruna ulaş → Başarı hikayelerini oku → Ret sayını tut → Fiziksel hareket et → 24 Saat Kuralı.',
          'SWSWSWN: Some Will, Some Won\'t, So What, Next — her "hayır" bir "evet"e yaklaştırıyor.',
          '24 Saat Kuralı: çok düşük hissediyorsan büyük karar alma; "bırakacağım" kararını 24 saat ertele.',
          'Motivasyon hedeften gelir — önce küçük adım at, motivasyon peşinden gelir.',
        ],
      },
    ],
  },
  {
    id: 'iletisim',
    baslik: 'İletişim & Takip',
    emoji: '🗣️',
    renk: 'bg-[#E1F5EE] dark:bg-[#0d3d2e] text-[#0F6E56] dark:text-[#4ade80] border-[#D2EFE4] dark:border-[#0d3d2e80]',
    konular: [
      {
        id: 'i1',
        baslik: 'İlk Konuşmayı Açmak',
        emoji: '👋',
        sure: '5 dk',
        seviye: 'Temel',
        ozet: 'Doğal bir konuşmayı nasıl fırsata dönüştürürsün.',
        maddeler: [
          'İnsanlar satış konuşması duymak istemez, hikâye duymak ister.',
          'Kendi değişimini anlat: "Ben de aynı durumdaydım…" ile başla.',
          'Soru sor, cevap verme: merak uyandır, zorla anlatma.',
          'Hedef: ilgi uyandırmak, bir sonraki adımı davet etmek.',
          '"Sana 2 dakikam var, ilgini çeker mi?" formülü çalışır.',
        ],
      },
      {
        id: 'i2',
        baslik: '2 Dakikalık Sunum',
        emoji: '⚡',
        sure: '7 dk',
        seviye: 'Orta',
        ozet: 'Kısa, güçlü ve akılda kalan bir sunum nasıl yapılır.',
        maddeler: [
          'Uzun sunum dikkat öldürür. 2 dakika yeterli, 20 dakika çok fazla.',
          'Yapı: Sorun → Çözüm → Kanıt → Davet.',
          'Rakam kullan: "3 ayda X TL" somut, "iyi para" muğlak.',
          'Öz hikâyeni ezberle: pratik yapar, pratik güven verir.',
          'Sunum bir kapı açar — her şeyi o kapının önünde anlatma.',
        ],
      },
      {
        id: 'i3',
        baslik: 'Takip Sanatı',
        emoji: '🔁',
        sure: '6 dk',
        seviye: 'Orta',
        ozet: '"Hayır" yerine "henüz hazır değilim" diyenleri kaybetmemek.',
        maddeler: [
          'Satışların %80\'i 5. temastan sonra gerçekleşir.',
          'İlk "hayır" karar değil, savunma refleksidir.',
          'Takip zamanlaması: 2 gün → 1 hafta → 1 ay → 3 ay.',
          'Her takipte yeni bir değer sun; sadece "düşündün mü?" deme.',
          'Takip etmek, baskı değil; ilgi ve değer sunmaktır.',
        ],
      },
      {
        id: 'tu1',
        baslik: '48 Saat Kuralı: Sunum Sonrası Takip',
        emoji: '⏱️',
        sure: '5 dk',
        seviye: 'Temel',
        ozet: 'Sunum bittikten sonra ilk 48 saat en yüksek ilgi zamanıdır — bu fırsatı kaçırma.',
        maddeler: [
          'Sunum biter bitmez 24-48 saat içinde takip et — bu süre en yüksek ilgi zamanı.',
          'Takip mesajı bir satış tekrarı değil, değer sunan bir devam: "Düşündükten sonra en büyük soru işaretin ne oldu?"',
          '"Hayır" aldıysan: ilişkiyi koru, kapıyı açık bırak, 30-90 gün sonra doğal bir sebeple tekrar yaz.',
          'Her takip yeni bir değer sunar — "Düşündün mü?" sorusu tek başına yetmez.',
          'Takip sistemi olmadan ekip büyümesi mümkün değildir.',
        ],
      },
      {
        id: 'tu2',
        baslik: '"Düşüneceğim" Diyene Ne Yazacaksın?',
        emoji: '💭',
        sure: '5 dk',
        seviye: 'Temel',
        ozet: '"Düşüneceğim" cevabı bir karar değil, gizli bir soru işaretidir — onu bul ve ele al.',
        maddeler: [
          '"Düşüneceğim" denilinceyi bir karar değil, gizli soru işareti olarak gör.',
          'Hemen sormayı bırakma — derine in: "Düşünürken en çok ne aklında kalıyor?"',
          'İlgili kısa bir içerik veya belge gönder — değer sun, sonra takip et.',
          '3 gün sonra nazik takip: "Fırsat buldun mu bakmaya?"',
          '"Düşüneyim" cevabı çoğu zaman para, zaman veya aile endişesi barındırır.',
        ],
      },
    ],
  },
  {
    id: 'davet',
    baslik: 'Davet & Aday Bulma',
    emoji: '🎯',
    renk: 'bg-[#F0F9FF] dark:bg-[#0c1a2e] text-[#0369A1] dark:text-[#38bdf8] border-[#BAE6FD] dark:border-[#0369a130]',
    konular: [
      {
        id: 'd1',
        baslik: 'Geniş Aday Listeni Nasıl Çıkarırsın?',
        emoji: '📋',
        sure: '7 dk',
        seviye: 'Temel',
        ozet: '"Kimseyi tanımıyorum" neredeyse hiç gerçek değildir — hafıza egzersizi ile liste 100\'ü geçer.',
        maddeler: [
          '"Kimseyi tanımıyorum" neredeyse hiç gerçek değildir — liste egzersizi bunu kanıtlar.',
          'İş çevresi: eski meslektaşlar, müşteriler, tedarikçiler.',
          'Sosyal çevre: okul arkadaşları, hobi grupları, spor arkadaşları.',
          'Dijital çevre: Instagram takipçileri, WhatsApp grupları, LinkedIn bağlantıları.',
          'İnsanları zihinsel olarak önceden reddetme — bu onların kararı, senin değil.',
        ],
      },
      {
        id: 'd2',
        baslik: 'Davet Sanatı: Tekliften Önce Merak',
        emoji: '🧲',
        sure: '6 dk',
        seviye: 'Temel',
        ozet: 'Çoğu davet erken teklif yüzünden başarısız olur — önce merak uyandır, sonra davet et.',
        maddeler: [
          'Çoğu davet başarısız olur çünkü çok erken teklif sunulur — önce merak uyandır.',
          '3 adım: 1) Gerçek bağlantı kur: "Ne yapıyorsun şu sıralar?" 2) Merak: "Buna bir bakmanı isterim." 3) Düşük baskı: "Sana göre olmayabilir, ama bir bak."',
          'Kaçın: "Muhteşem fırsat" abartısı, "Para kazanmak ister misin?" tuzağı, "Hayatın değişecek" vaadi.',
          'İnsanlar fikir satın almaktan hoşlanır ama satış yapıldığını hissetmekten nefret eder.',
          'Merak yarat; onların sana gelmesine izin ver.',
        ],
      },
      {
        id: 'd3',
        baslik: 'WhatsApp İlk Mesaj Senaryoları',
        emoji: '💬',
        sure: '8 dk',
        seviye: 'Temel',
        ozet: 'Bu taslakları kişiselleştirerek kullan — genel toplu mesaj gönderme.',
        maddeler: [
          'Her mesajı kişiselleştir: isim + gerçek bir bağlantı noktası kullan.',
          'Senaryo 1 (uzun görüşmemişsin): "Merhaba [İsim], dün aklıma geldin. Nasılsın?"',
          'Senaryo 2 (eski iş arkadaşı): "Eski şirketten düşünüyorum. Her şey nasıl gidiyor?"',
          'Senaryo 3 (ek gelir istemişti): "Bir ara ek gelir istediğinden bahsetmiştin, hala aklında mı?"',
          'Asla toplu spam mesaj gönderme — 1\'e 1 hissettiren kişisel mesaj çalışır.',
        ],
      },
    ],
  },
  {
    id: 'sunum',
    baslik: 'Sunum & Kapanış',
    emoji: '🎤',
    renk: 'bg-[#FFF7ED] dark:bg-[#2a1500] text-[#9A3412] dark:text-[#fb923c] border-[#FED7AA] dark:border-[#9a341230]',
    konular: [
      {
        id: 'sk1',
        baslik: '20 Dakikada Etkili Sunum: T-S-P-O-C',
        emoji: '📊',
        sure: '10 dk',
        seviye: 'Orta',
        ozet: 'Uzun sunumlar yerine beş parçalı T-S-P-O-C arki: güven, durum, plan, fırsat ve davet.',
        maddeler: [
          'T (Güven, 0-3 dk): Anlat değil, dinle — "Şu an en çok ne önemli senin için?"',
          'S (Durum, 3-7 dk): Onların sözünü kullanarak acı noktasını yansıt — anlaşıldıklarını hissettir.',
          'P (Plan, 7-13 dk): Ürün/fırsatı, durumlarına doğrudan cevap olarak sun; özellik değil fayda.',
          'O (Fırsat, 13-17 dk): Somut ve belgelenebilir değişimi hayalleştir — abartma.',
          'C (Davet, 17-20 dk): Büyük karar değil, tek küçük adım — "10 gün dene" veya "Bir zoom\'a gel."',
        ],
      },
      {
        id: 'sk2',
        baslik: 'Kapanışın 5 Tekniği',
        emoji: '🔐',
        sure: '8 dk',
        seviye: 'Orta',
        ozet: 'Kapanış zorlamak değil, karar vermeyi kolaylaştırmaktır — baskısız beş saha tekniği.',
        maddeler: [
          '1-10 Ölçeği: "1-10 arası neredesin?" → 4-7 ise: "Seni 10\'dan ne tutuyor?"',
          '"Eğer... olsaydı..." sorusu: "Zaman engel olmasa ilerler miydin?" — gerçek engeli yüzeye çıkar.',
          'Sessizlik tekniği: teklifi yap, sus ve bekle. Konuşmak için üretilen baskı genellikle satın alma değil, direnç üretir.',
          'Sonraki adım kapanışı: "Her şeyi şimdi karara bağlamanı değil, sadece bir küçük adım atmayı kastediyorum."',
          'Özet + davet: 3 faydayı özetle, düşük riskli tek bir aksiyon öner.',
        ],
      },
      {
        id: 'sk3',
        baslik: 'İtiraz Karşılama: Hisset–Hissetmiş–Buldu & DDSID',
        emoji: '🧩',
        sure: '10 dk',
        seviye: 'Orta',
        ozet: 'İtirazı duy, savunmaya geçme, önce gerçek endişeyi bul, sonra hikâyeyle ilerle.',
        maddeler: [
          'Hisset–Hissetmiş–Buldu: duyguyu yansıt → benzer deneyimi hatırlat → üçüncü kişi örneğiyle ilerle.',
          'Soğan soyma: Dur → Yumuşak onay ("Haklısın, önemli") → Derinleştir ("Bu endişenin kaynağı ne?") → Sabitle.',
          'DDSID: Durdur → Doğrula → Sor → İkna değil Hikâye → Davet.',
          'İlk cümlede tartışmaya girme; ezberlenmiş robot cevap verme.',
          'Abartılı gelir iddiasından kaçın; kısa ve gerçek bir kişisel hikaye kullan.',
        ],
      },
    ],
  },
  {
    id: 'ekip',
    baslik: 'Ekip & Liderlik',
    emoji: '👥',
    renk: 'bg-[#FAEEDA] dark:bg-[#3a2200] text-[#854F0B] dark:text-[#fbbf24] border-[#F6E4C4] dark:border-[#3a220080]',
    konular: [
      {
        id: 'e1',
        baslik: 'Ekip Kurmak: İlk Adımlar',
        emoji: '🏗️',
        sure: '5 dk',
        seviye: 'Orta',
        ozet: 'Sıfırdan bir ekip inşa etmenin sağlam temelleri.',
        maddeler: [
          'Herkesi değil, doğru insanı ara: hırslı, iletişime açık, güvenilir.',
          'İlk 2–3 kişini doğru seç — onlar kültürünü belirler.',
          'Yeni üyeye ilk 48 saat kritik: hemen aksiyon almasını sağla.',
          'Mentor değil, model ol: kendin yapmazsan ekibin yapmaz.',
          'Duygusal destek ve teknik koçluk arasındaki dengeyi kur.',
        ],
      },
      {
        id: 'e2',
        baslik: 'Çoğaltma: Sistemle Büyümek',
        emoji: '🔄',
        sure: '8 dk',
        seviye: 'İleri',
        ozet: 'Sen olmadan da büyüyen bir ekip nasıl inşa edilir.',
        maddeler: [
          'Çoğaltma: başkasının yapabildiği şeyi sisteme bağlamak.',
          'Tek bir süper yıldıza bağlı ekip kırılgandır; sistem güçlü olmalı.',
          '"Eğitimimi ver, git kendi kendin çalış" formülü çalışır.',
          'Her üye kendi 2–3 kişisini bulana kadar destek ver.',
          'Büyük liderler ekibini bağımlı değil, bağımsız yapar.',
        ],
      },
      {
        id: 'e3',
        baslik: 'İlk 5 Ekip Üyeni Nasıl Seçersin?',
        emoji: '🔎',
        sure: '9 dk',
        seviye: 'Orta',
        ozet: 'Kolay üye değil, doğru üye bulmak — ilk 5 kişi kültürünü belirler.',
        maddeler: [
          'Herkesi değil, doğru kişiyi ara: hırslı, koçlanabilir, güvenilir.',
          'Aday değerlendirme soruları: Bu kişi sahada çalışır mı? Öğrenmeye açık mı? Sözünü tutar mı?',
          'İlk 5, ekip kültürünü belirler — seçimde aceleci olma.',
          'İlk üye: yakın çevrenden, hazır ve motive olan biri. Sonraki üyeler farklı ağlardan.',
          'Kolay üye bulmak değil, doğru üye bulmak öncelik.',
        ],
      },
      {
        id: 'e4',
        baslik: 'Duplikasyon Sistemi: Seni Değil, Sistemi Kopyalat',
        emoji: '📡',
        sure: '10 dk',
        seviye: 'İleri',
        ozet: 'Duplikasyon, kişisel karizmanı değil, tekrarlanabilir bir sistemi ekibine aktarmaktır.',
        maddeler: [
          'Duplikasyon: senin yapabildiğini sisteme bağlamak, başkasının da yapabilmesi için.',
          'En basit başlangıç akışını tek A4\'e sığdır ve yeni üyeye anlat — geri anlattır.',
          'Tek süper yıldıza bağlı ekip kırılgandır — sisteme bağlı ekip güçlüdür.',
          '"Eğitimimi ver, git kendi kendin çalış" formülü sürdürülebilir büyüme sağlar.',
          'Büyük liderler ekibini bağımlı değil, bağımsız yapar.',
        ],
      },
    ],
  },
  {
    id: 'strateji',
    baslik: 'Strateji & Büyüme',
    emoji: '📈',
    renk: 'bg-[#FBEAF0] dark:bg-[#3d0f1f] text-[#72243E] dark:text-[#f9a8d4] border-[#F5D9E5] dark:border-[#3d0f1f80]',
    konular: [
      {
        id: 's1',
        baslik: 'Günlük 5 Eylem Prensibi',
        emoji: '5️⃣',
        sure: '4 dk',
        seviye: 'Temel',
        ozet: 'Her gün sadece 5 eylem ile tutarlı büyüme.',
        maddeler: [
          '5 yeni kişiyle tanış veya eski biriyle tekrar konuş.',
          'Bir sunum veya bilgilendirme yap.',
          'Bir takip mesajı gönder.',
          'Ürününü kullan ve deneyimini not et.',
          'Bir şey öğren: video, podcast, kitap — 15 dakika yeter.',
        ],
      },
      {
        id: 's2',
        baslik: 'Sosyal Medyayı İş Aracına Dönüştürmek',
        emoji: '📱',
        sure: '7 dk',
        seviye: 'Orta',
        ozet: 'Spam değil, değer içeriğiyle organik büyüme.',
        maddeler: [
          'Ürün/fırsat paylaşımı değil, dönüşüm hikâyeleri paylaş.',
          '80/20 kuralı: %80 değer içeriği, %20 iş içeriği.',
          'DM stratejisi: sormadan önce ilgi göster, dinle, sonra davet et.',
          'Günde 1 story + haftada 2–3 gönderi sürdürülebilir hedeftir.',
          'Rakam + sonuç + duygu: "3 ayda X TL + ne hissettim" formülü güçlü.',
        ],
      },
      {
        id: 's3',
        baslik: '90 Günlük Başlangıç Planı',
        emoji: '🗓️',
        sure: '6 dk',
        seviye: 'Temel',
        ozet: 'İlk 90 günde ne yapmalı, ne yapmamalı.',
        maddeler: [
          '1–30. gün: Öğren, dene, listeyi yaz. Ürünü kendin kullan.',
          '31–60. gün: İlk 10 konuşmayı tamamla, ilk satışı veya üyeyi al.',
          '61–90. gün: İlk ekip üyeni mentor et, sistemi çoğalt.',
          'Bu dönemde tek odak: momentum kırmamak.',
          '90 günün sonunda bir değerlendirme yap ve bir sonraki 90 günü planla.',
        ],
      },
      {
        id: 's4',
        baslik: 'Instagram\'da Kişisel Marka Kurmak',
        emoji: '📸',
        sure: '7 dk',
        seviye: 'Orta',
        ozet: 'Instagram\'ı doğru kullanmak, sana gelen sıcak adaylar yaratır — spam değil, çekim merkezi ol.',
        maddeler: [
          'İçerik karması: 3 eğitici + 2 kişisel + 1 iş/ürün paylaşımı (3-2-1 kuralı).',
          'Spam DM atmak yerine doğal konuşmalar başlat — asla izinsiz toplu teklif gönderme.',
          'Çekim merkezi ol: insanlar seni izledikçe gün gelir sorarlar, o anda hazır ol.',
          'Kendi sesi, kendi yüzü, kendi hikayesi — başkasının içeriğini kopyalama.',
          'Takipçilerle gerçek ilişki kur; içeriklerin kapı açar, sen orada hazır ol.',
        ],
      },
      {
        id: 's5',
        baslik: 'Sosyal Medyada YAPILMAYACAKLAR',
        emoji: '🚫',
        sure: '5 dk',
        seviye: 'Temel',
        ozet: 'Hızlı referans: sosyal medyada seni yakacak hatalar ve doğruları. Sahada uygula.',
        maddeler: [
          '❌ Spam DM: hesabını ve güveni tehlikeye atar. ✅ Değer ver, bek, sorular gelince cevapla.',
          '❌ Sadece ürün/fırsat paylaşmak. ✅ 3-2-1 kuralı: 3 değer, 2 kişisel, 1 iş.',
          '❌ Abartılı kazanç paylaşımları. ✅ Şirketin onaylı, ölçülü dilini kullan.',
          '❌ Başkasının içeriğini kopyalamak. ✅ Kendi sesi, kendi yüzü, kendi hikayesi.',
          '❌ Olumsuz yorumlarla açık tartışmak. ✅ Özelden çöz veya kibarca geç.',
        ],
      },
    ],
  },
  {
    id: 'uyum',
    baslik: 'Uyum & Etik',
    emoji: '⚖️',
    renk: 'bg-[#F0FDF4] dark:bg-[#052e16] text-[#166534] dark:text-[#86efac] border-[#BBF7D0] dark:border-[#16653430]',
    konular: [
      {
        id: 'ue1',
        baslik: 'Türkiye\'de Doğrudan Satış: Özet Çerçeve',
        emoji: '🏛️',
        sure: '8 dk',
        seviye: 'Temel',
        ozet: 'Yasal sınırları bilmek seni hem korur hem güvenilir yapar — genel çerçeve.',
        maddeler: [
          'Sağlık ürünlerinde: tanı/tedavi vaadi, garanti sonuç ve "kesin iyileşir" ifadeleri yüksek risk taşır.',
          'Meşru iş için kontrol: Gerçek müşteriye satılan ürün var mı? Kazanç vaadi belgelenebilir mi?',
          'Piramit belirtisi: ürün yok veya sembolik; gelir çoğunlukla kayıttan besleniyor.',
          'Abartılı kazanç, garanti sağlık sonucu ve belgesiz "onaylıdır" iddialarından kaçın.',
          'Bu özet genel çerçevedir; detay için şirketinin uyum kaynaklarına başvur.',
        ],
      },
      {
        id: 'ue2',
        baslik: 'Sağlık Ürünleri: Söylenebilen / Söylenemeyen',
        emoji: '🩺',
        sure: '4 dk',
        seviye: 'Temel',
        ozet: 'Yasal açıdan güvende kalmak için hızlı referans — hangi cümleleri kullanabilir, hangilerinden kaçınmalısın.',
        maddeler: [
          '✅ Söylenebilir: "Bende şu etkiyi yaptı", "Deneyimimi paylaşabilirim", "Sertifika bilgisini verebilirim".',
          '❌ Söylenemez: "Hastalığı iyileştirir", "Kesinlikle işe yarar", "Doktor onaylıdır" (belgesiz).',
          'Kişisel sonuç ≠ herkes için garanti — bunu her zaman belirt.',
          '"Kendi deneyimim şuydu..." ile başla; tıbbi iddia ve garantiden kaçın.',
          'Şirketinin onay aldığı ifade kalıplarını kullan.',
        ],
      },
      {
        id: 'ue3',
        baslik: 'Dijital Paylaşım ve Beyanlar: Kısa Kontrol',
        emoji: '📲',
        sure: '6 dk',
        seviye: 'Temel',
        ozet: 'Profil, hikaye ve mesajda güvende kal — kazanç, sağlık ve kişisel veri için temel hatırlatmalar.',
        maddeler: [
          'Kazanç: "X sürede Y kazanç" iddiası hem güven hem uyum riski taşır — ölçülü dil kullan.',
          'Sağlık: "Kendi deneyimim şuydu..." ile başla; tıbbi iddia ve garantiden kaçın.',
          'KVKK: İzinsiz kişisel veri paylaşma; gereksiz kişi listesi aktarımı yok.',
          'Mesafeli satış: Şirketinin sipariş ve cayma sürecini doğru anlat.',
          'Şeffaf, ölçülü, şirket uyumuna yakın dil → uzun vadeli güven.',
        ],
      },
    ],
  },
  {
    id: 'urun',
    baslik: 'Ürün & Şirket',
    emoji: '🏢',
    renk: 'bg-[#FAF5FF] dark:bg-[#1a0030] text-[#6B21A8] dark:text-[#d8b4fe] border-[#E9D5FF] dark:border-[#6b21a830]',
    konular: [
      {
        id: 'us1',
        baslik: 'Şüpheden İnanca: Ürünü Deneyimleyen Distribütörün Hikayesi',
        emoji: '✨',
        sure: '8 dk',
        seviye: 'Orta',
        ozet: 'Ürüne inanmadan bu işe başlamak hem sürdürülemez hem etik değildir — kendi hikayeni bul.',
        maddeler: [
          'Ürüne inanmadan bu işi yapmak hem sürdürülemez hem de etik değildir.',
          'Ürünü kendin ve ailenle kullan; 30 gün boyunca sonuçları not al.',
          '"Bende şu etkiyi yaptı; senin deneyimin farklı olabilir" — senaryo değil, gerçek hikaye.',
          'Ürün deneyimi satış tekniğinin yerini tutar; hikayeniz varsa script\'e gerek azalır.',
          'Etik inanç = sürdürülebilir iş. İnanmadığın bir şeyi satmak yorucu ve çöküşe neden olur.',
        ],
      },
      {
        id: 'us2',
        baslik: 'Şirketi Tanımak: Güveni İnşa Etmenin Temeli',
        emoji: '🔬',
        sure: '7 dk',
        seviye: 'Temel',
        ozet: 'Adayların güven soruları şirkete yönelir — bu soruları cevaplamak güven inşasıdır.',
        maddeler: [
          'Adaylar güvensizlik hissettiklerinde soruları şirkete yönelir — bu soruları cevaplamak güven inşasıdır.',
          'Bilmen gereken 5 alan: kuruluş tarihi, ürün portföyü, yasal kayıtlar, kompanzasyon planı şeffaflığı, destek altyapısı.',
          'Adayı birincil kaynağa yönlendir: "Buraya bak, bu sayfada var."',
          'Bağımsız kaynaklardaki değerlendirmeleri oku; yalnızca şirketin anlattıklarına güvenme.',
          'Bilgili distribütör = güvenilir distribütör.',
        ],
      },
    ],
  },
]

const EN_KATEGORILER: Kategori[] = [
  {
    id: 'zihniyet',
    baslik: 'Mindset & Foundation',
    emoji: '🧠',
    renk: 'bg-[#EEF2FF] dark:bg-[#1e1b4b] text-[#3730A3] dark:text-[#a5b4fc] border-[#E0E7FF] dark:border-[#312e8130]',
    konular: [
      {
        id: 'z1',
        baslik: 'What is Network Marketing?',
        emoji: '🌐',
        sure: '5 min',
        seviye: 'Basic',
        ozet: 'The true definition of the business, described simply and debunking the myths.',
        maddeler: [
          'NM is the combination of direct sales and the personal recommendation economy.',
          'The company pays the advertising budget to distributors as commissions.',
          'Earnings come from two sources: your own sales and your team\'s sales.',
          'In legitimate NM, the product is real, consumption is continuous, and growth is sustainable.',
          'Difference from pyramid schemes: in NM, you can bypass those who joined before you.',
        ],
      },
      {
        id: 'z2',
        baslik: 'Why Do Most People Quit?',
        emoji: '🚶',
        sure: '4 min',
        seviye: 'Basic',
        ozet: 'The truth behind the statistics and how to rise above them.',
        maddeler: [
          'Most people quit in their first 90 days — due to false expectations.',
          'NM is a marathon, not a sprint; it requires slow but strong compound growth.',
          'Social pressure and initial rejections are the most common reasons to quit.',
          'The persistent 20% earn 80% of the total revenue — this is true in every industry.',
          'The solution: find a clear "why" and work closely with your sponsor.',
        ],
      },
      {
        id: 'z3',
        baslik: 'Growth Mindset',
        emoji: '🌱',
        sure: '6 min',
        seviye: 'Basic',
        ozet: 'Escaping the fixed mindset trap and practicing openness to growth.',
        maddeler: [
          '"I am not a natural salesperson" is a fixed mindset trap.',
          'Skills can be learned — communication, inviting, follow-up, and leadership.',
          'Every rejection brings you one step closer to a "yes".',
          'Do not take feedback personally: "no" is not about you, it is about their timing.',
          'Let books, podcasts, and observation be your daily mental "workout".',
        ],
      },
      {
        id: 'z4',
        baslik: 'The Truth About "No": What Rejection Really Means',
        emoji: '🛡️',
        sure: '5 min',
        seviye: 'Basic',
        ozet: 'Fear of rejection is the biggest blocker in NM — learn how to reframe "no."',
        maddeler: [
          '"No" is usually aimed at timing, bandwidth, or clarity—not your worth.',
          'Types of "no": "not now" → reconnect later; "not this way" → adjust approach; "never" → preserve the relationship.',
          'Talk to five people this week; even after a "no," leave the door open.',
          'Ask: "When would it feel okay if I checked back?" No pressure—just clarity.',
          'Fear of rejection rarely hurts as much as never starting. Inaction is the bigger risk.',
        ],
      },
      {
        id: 'z5',
        baslik: 'What to Do When Motivation Drops',
        emoji: '🔋',
        sure: '7 min',
        seviye: 'Basic',
        ozet: 'Motivation fluctuates—that\'s normal. Seven practical tools and the SWSWSWN framework to get back on rhythm.',
        maddeler: [
          'Motivation loss is a clarity problem—"I forgot why I\'m doing this," not a lack of energy.',
          '7 tools: Refresh your "why" list → Create a small win → Reach your mentor → Read success stories → Track your rejections → Move physically → Apply the 24-hour rule.',
          'SWSWSWN: Some Will, Some Won\'t, So What, Next—every "no" moves you closer to "yes."',
          '24-hour rule: if you feel very low, don\'t make big decisions. Delay the "I\'ll quit" thought by 24 hours.',
          'Motivation follows action—take one small step first; motivation usually follows.',
        ],
      },
    ],
  },
  {
    id: 'iletisim',
    baslik: 'Communication & Follow-Up',
    emoji: '🗣️',
    renk: 'bg-[#E1F5EE] dark:bg-[#0d3d2e] text-[#0F6E56] dark:text-[#4ade80] border-[#D2EFE4] dark:border-[#0d3d2e80]',
    konular: [
      {
        id: 'i1',
        baslik: 'Opening the First Conversation',
        emoji: '👋',
        sure: '5 min',
        seviye: 'Basic',
        ozet: 'How to turn a natural conversation into a business opportunity.',
        maddeler: [
          'People do not want to hear a sales pitch, they want to hear a story.',
          'Share your own transformation: start with "I used to be in the exact same position..."',
          'Ask questions, do not just give answers: build curiosity, do not force the talk.',
          'Goal: spark interest and invite them to take the next step.',
          'The "I only have 2 minutes, but does this interest you?" formula works wonders.',
        ],
      },
      {
        id: 'i2',
        baslik: 'The 2-Minute Presentation',
        emoji: '⚡',
        sure: '7 min',
        seviye: 'Medium',
        ozet: 'How to deliver a short, powerful, and memorable presentation.',
        maddeler: [
          'Long presentations kill attention. 2 minutes is enough, 20 minutes is too much.',
          'Structure: Problem → Solution → Proof → Invitation.',
          'Use real numbers: "X dollars in 3 months" is concrete; "good money" is vague.',
          'Memorize and practice your core story: practice builds ultimate confidence.',
          'A presentation opens a door — do not try to explain everything on the doorstep.',
        ],
      },
      {
        id: 'i3',
        baslik: 'The Art of Follow-Up',
        emoji: '🔁',
        sure: '6 min',
        seviye: 'Medium',
        ozet: 'How not to lose those who say "I\'m not ready yet" instead of "no".',
        maddeler: [
          '80% of sales occur after the 5th contact/follow-up.',
          'An initial "no" is not a final decision, it is a natural defense reflex.',
          'Follow-up timing: 2 days → 1 week → 1 month → 3 months.',
          'Deliver new value in every follow-up; do not just ask "did you think about it?"',
          'Following up is not pressure; it is offering care and continuous value.',
        ],
      },
      {
        id: 'tu1',
        baslik: 'The 48-Hour Rule: Following Up After Your Presentation',
        emoji: '⏱️',
        sure: '5 min',
        seviye: 'Basic',
        ozet: 'The first 48 hours after a presentation are when interest is highest—don\'t miss this window.',
        maddeler: [
          'Follow up within 24–48 hours after a presentation—that\'s when interest is at its peak.',
          'Your follow-up isn\'t a repeated pitch; it\'s value-adding continuation: "After thinking it over, what\'s the one question still on your mind?"',
          'After a "no": preserve the relationship, leave the door open, reconnect naturally in 30–90 days.',
          'Every follow-up delivers new value—"Did you think about it?" alone isn\'t enough.',
          'Without a follow-up system, team growth is impossible.',
        ],
      },
      {
        id: 'tu2',
        baslik: 'What to Write When They Say "I\'ll Think About It"',
        emoji: '💭',
        sure: '5 min',
        seviye: 'Basic',
        ozet: '"I\'ll think about it" is not a decision—it hides a specific concern. Find it and address it.',
        maddeler: [
          '"I\'ll think about it" is not a decision—it hides a specific question or concern.',
          'Don\'t drop it; go deeper: "While you think, what\'s the one thing sticking most?"',
          'Send a relevant piece of content or document to add value.',
          'Three days later, a gentle nudge: "Did you get a chance to look?"',
          '"Think about it" usually holds a concern about money, time, or family.',
        ],
      },
    ],
  },
  {
    id: 'davet',
    baslik: 'Inviting & Prospecting',
    emoji: '🎯',
    renk: 'bg-[#F0F9FF] dark:bg-[#0c1a2e] text-[#0369A1] dark:text-[#38bdf8] border-[#BAE6FD] dark:border-[#0369a130]',
    konular: [
      {
        id: 'd1',
        baslik: 'How to Build Your Wide Prospect Name List',
        emoji: '📋',
        sure: '7 min',
        seviye: 'Basic',
        ozet: '"I know nobody" is almost never true—a memory exercise will prove it.',
        maddeler: [
          '"I know nobody" is almost never literally true—a memory exercise proves it.',
          'Work: former colleagues, clients, suppliers, industry acquaintances.',
          'Social: school friends, neighbors, hobby groups, sports contacts.',
          'Digital: people you actually know from Instagram, WhatsApp groups, LinkedIn.',
          'Don\'t pre-reject people mentally ("they\'ll say no")—that\'s their decision, not yours.',
        ],
      },
      {
        id: 'd2',
        baslik: 'The Art of the Invite: Curiosity Before the Pitch',
        emoji: '🧲',
        sure: '6 min',
        seviye: 'Basic',
        ozet: 'Most invites fail because people pitch too early—create curiosity first, then invite.',
        maddeler: [
          'Most invites fail because people pitch too early—lead with curiosity, not the offer.',
          '3 steps: 1) Connect for real: "What are you up to lately?" 2) Spark curiosity: "I\'d love your eyes on something." 3) Low pressure: "It might not be for you—just take a quick look."',
          'Avoid: "Huge opportunity" hype, "Want to earn money?" traps, "Your life will change" promises.',
          'People like buying ideas—but hate feeling sold.',
          'Create curiosity and let them lean in.',
        ],
      },
      {
        id: 'd3',
        baslik: 'WhatsApp First Message Scripts',
        emoji: '💬',
        sure: '8 min',
        seviye: 'Basic',
        ozet: 'Personalize these openers—never blast generic spam.',
        maddeler: [
          'Personalize every message: name + one real anchor. Never blast generic spam.',
          'Scenario 1 (haven\'t spoken lately): "Hi [Name]—you popped into my head. How are you?"',
          'Scenario 2 (former coworker): "Thinking about [Company] days. How\'s everything going?"',
          'Scenario 3 (once mentioned extra income): "You mentioned wanting side income—is that still on your radar?"',
          'Name + real anchor = 1:1 feeling. That\'s what makes messages work.',
        ],
      },
    ],
  },
  {
    id: 'sunum',
    baslik: 'Presenting & Closing',
    emoji: '🎤',
    renk: 'bg-[#FFF7ED] dark:bg-[#2a1500] text-[#9A3412] dark:text-[#fb923c] border-[#FED7AA] dark:border-[#9a341230]',
    konular: [
      {
        id: 'sk1',
        baslik: 'T-S-P-O-C: A 20-Minute Presentation Framework',
        emoji: '📊',
        sure: '10 min',
        seviye: 'Medium',
        ozet: 'Instead of marathon talks, use a five-part arc that ends in clarity, not confusion.',
        maddeler: [
          'T (Trust, 0–3 min): Listen before you talk. "What matters most to you right now?"',
          'S (Situation, 3–7 min): Reflect the pain point they named—make them feel understood.',
          'P (Plan, 7–13 min): Present the product or opportunity as a direct answer to their situation.',
          'O (Opportunity, 13–17 min): Paint the concrete change in their life—only realistic, documentable outcomes.',
          'C (Call-to-Action, 17–20 min): One small next step—not a big decision. "Try for 10 days" or "Join one Zoom."',
        ],
      },
      {
        id: 'sk2',
        baslik: 'The 5 Closing Techniques That Work Without Pressure',
        emoji: '🔐',
        sure: '8 min',
        seviye: 'Medium',
        ozet: 'Closing isn\'t coercion—it\'s making decisions easier. Five field-tested techniques.',
        maddeler: [
          '1-10 Scale: "On a scale of 1–10, where are you right now?" If 4–7: "What\'s keeping you from a 10?"',
          '"If...then..." question: surfaces the real objection without confrontation.',
          'Silence technique: make the offer, then stop talking and wait.',
          'Next-step close: "I\'m not asking you to decide everything now—just the next small step."',
          'Summary + invite: summarize 3 key benefits, propose one low-risk action.',
        ],
      },
      {
        id: 'sk3',
        baslik: 'Objection Handling: Feel-Felt-Found & VVSSD',
        emoji: '🧩',
        sure: '10 min',
        seviye: 'Medium',
        ozet: 'Hear the objection, don\'t get defensive, find the real concern first, then move forward with story.',
        maddeler: [
          'Feel–Felt–Found: reflect the emotion → recall a similar experience → share a third-person example.',
          'Peeling the onion: Stop → Soft validation ("That\'s fair") → Deepen ("What\'s behind that concern?") → Anchor.',
          'VVSSD: Validate → Verify → Seek → Story (not persuasion) → Door (invite).',
          'Don\'t jump into debate on the first response; avoid scripted robot answers.',
          'No exaggerated income claims; use a short genuine personal story instead.',
        ],
      },
    ],
  },
  {
    id: 'ekip',
    baslik: 'Team & Leadership',
    emoji: '👥',
    renk: 'bg-[#FAEEDA] dark:bg-[#3a2200] text-[#854F0B] dark:text-[#fbbf24] border-[#F6E4C4] dark:border-[#3a220080]',
    konular: [
      {
        id: 'e1',
        baslik: 'Building a Team: First Steps',
        emoji: '🏗️',
        sure: '5 min',
        seviye: 'Medium',
        ozet: 'The solid foundations of building a team from scratch.',
        maddeler: [
          'Do not look for everyone, look for the right ones: ambitious, coachable, reliable.',
          'Choose your first 2–3 partners carefully — they will define your team culture.',
          'The first 48 hours are critical for a new member: get them to take action immediately.',
          'Be a role model, not just a advisor: if you do not do it, your team won\'t either.',
          'Establish a healthy balance between emotional support and technical coaching.',
        ],
      },
      {
        id: 'e2',
        baslik: 'Duplication: Scaling with a System',
        emoji: '🔄',
        sure: '8 min',
        seviye: 'Advanced',
        ozet: 'How to build a team that grows even when you are not there.',
        maddeler: [
          'Duplication: connecting things that others can also do to a systematic process.',
          'A team relying on a single superstar is fragile; a team relying on a system is strong.',
          'The "I will train you, then model it, then let you fly" formula is highly successful.',
          'Support every member until they find and sponsor their own first 2–3 partners.',
          'Great leaders make their team independent, not dependent.',
        ],
      },
      {
        id: 'e3',
        baslik: 'How to Choose Your First 5 Team Members',
        emoji: '🔎',
        sure: '9 min',
        seviye: 'Medium',
        ozet: 'Find the right member, not the easiest one—your first 5 define your team culture.',
        maddeler: [
          'Look for the right person, not everyone: ambitious, coachable, reliable.',
          'Evaluation questions: Will this person work in the field? Are they open to learning? Do they keep their word?',
          'Your first 5 define your team culture—don\'t rush the selection.',
          'First member: someone close, ready, and motivated. Later members from different networks.',
          'Priority is finding the right member, not the easiest one.',
        ],
      },
      {
        id: 'e4',
        baslik: 'Duplication System: Build a Team That Copies the System, Not You',
        emoji: '📡',
        sure: '10 min',
        seviye: 'Advanced',
        ozet: 'Duplication means transferring a repeatable system to your team—not your personal charisma.',
        maddeler: [
          'Duplication: connecting what you do to a system so others can do it too.',
          'Fit your simplest starting workflow onto one A4 page—teach it, then have them teach it back.',
          'A team relying on a single superstar is fragile; a system-reliant team is strong.',
          'The "I\'ll train you, then let you run" formula creates sustainable growth.',
          'Great leaders make their team independent, not dependent.',
        ],
      },
    ],
  },
  {
    id: 'strateji',
    baslik: 'Strategy & Momentum',
    emoji: '📈',
    renk: 'bg-[#FBEAF0] dark:bg-[#3d0f1f] text-[#72243E] dark:text-[#f9a8d4] border-[#F5D9E5] dark:border-[#3d0f1f80]',
    konular: [
      {
        id: 's1',
        baslik: 'The Daily 5 Actions Principle',
        emoji: '5️⃣',
        sure: '4 min',
        seviye: 'Basic',
        ozet: 'Achieving consistent business growth with just 5 simple daily actions.',
        maddeler: [
          'Meet 5 new people or reconnect with 5 existing contacts.',
          'Share a presentation or short informational overview.',
          'Send 1 follow-up message to a prospect.',
          'Use your product and note down your personal experience.',
          'Learn something new: watch a video, listen to a podcast, read — 15 minutes is enough.',
        ],
      },
      {
        id: 's2',
        baslik: 'Turning Social Media Into a Business Tool',
        emoji: '📱',
        sure: '7 min',
        seviye: 'Medium',
        ozet: 'Achieving organic growth with valuable content instead of spamming.',
        maddeler: [
          'Do not just share product spam; share stories of transformation and benefits.',
          'The 80/20 rule: 80% valuable/educational content, 20% direct business promotion.',
          'DM strategy: show genuine interest first, listen actively, and then invite.',
          'A sustainable goal is 1 story a day + 2–3 main grid posts a week.',
          'The "Number + Result + Emotion" formula is highly engaging.',
        ],
      },
      {
        id: 's3',
        baslik: '90-Day Quickstart Plan',
        emoji: '🗓️',
        sure: '6 min',
        seviye: 'Basic',
        ozet: 'What to do and what to avoid in your critical first 90 days.',
        maddeler: [
          'Days 1–30: Learn the ropes, use the product yourself, and write down your prospect list.',
          'Days 31–60: Complete your first 10 invite calls, make your first sale or sign up a member.',
          'Days 61–90: Mentor your first distributor and begin duplicating the system.',
          'Your only focus during this period: maintaining active, unstoppable momentum.',
          'Evaluate your progress at the end of the 90 days and plan the next 90-day block.',
        ],
      },
      {
        id: 's4',
        baslik: 'Building Personal Brand on Instagram',
        emoji: '📸',
        sure: '7 min',
        seviye: 'Medium',
        ozet: 'Used correctly, Instagram creates warm inbound leads—be a pull center, not a pusher.',
        maddeler: [
          'Content mix: 3 educational + 2 personal + 1 business/product posts (the 3-2-1 rule).',
          'Start natural conversations—never send unsolicited bulk DMs.',
          'Be an attraction center: as people follow you, they eventually ask—be ready.',
          'Your voice, your face, your story—don\'t copy others\' content.',
          'Build real relationships with followers; your content opens the door, you walk through it.',
        ],
      },
      {
        id: 's5',
        baslik: 'Social Media: What NOT to Do',
        emoji: '🚫',
        sure: '5 min',
        seviye: 'Basic',
        ozet: 'Quick reference: the mistakes that will damage your brand, and what to do instead.',
        maddeler: [
          '❌ Spam DMs risk your account and trust. ✅ Add value first; answer questions when they come.',
          '❌ Only posting products/opportunity. ✅ 3-2-1: 3 value, 2 personal, 1 business.',
          '❌ Exaggerated earnings posts. ✅ Use measured, company-approved language.',
          '❌ Copying others\' content. ✅ Your voice, your face, your story.',
          '❌ Public arguments with critics. ✅ Resolve privately or move on politely.',
        ],
      },
    ],
  },
  {
    id: 'uyum',
    baslik: 'Compliance & Ethics',
    emoji: '⚖️',
    renk: 'bg-[#F0FDF4] dark:bg-[#052e16] text-[#166534] dark:text-[#86efac] border-[#BBF7D0] dark:border-[#16653430]',
    konular: [
      {
        id: 'ue1',
        baslik: 'Direct Sales in Turkey: A Quick Compliance Framework',
        emoji: '🏛️',
        sure: '8 min',
        seviye: 'Basic',
        ozet: 'Knowing the legal boundaries protects you and makes you more trustworthy—general overview.',
        maddeler: [
          'Health products: diagnosis/treatment promises and guaranteed results carry high legal risk.',
          'Legitimacy check: real product sold to real customers? Income claims documentable?',
          'Pyramid warning signal: no/symbolic product; income mostly from recruiting, not sales.',
          'Avoid exaggerated earnings, guaranteed health outcomes, undocumented "approved" claims.',
          'This is a general framework—consult your company\'s official compliance resources for specifics.',
        ],
      },
      {
        id: 'ue2',
        baslik: 'Health Products: What You Can and Cannot Say',
        emoji: '🩺',
        sure: '4 min',
        seviye: 'Basic',
        ozet: 'Quick reference for staying legally safe—which phrases work, which ones create risk.',
        maddeler: [
          '✅ You can say: "Here\'s what I personally experienced," "I can share certifications," "My experience was..."',
          '❌ Never say: "It cures diseases," "It definitely works," "Doctor-approved" (without documentation).',
          'Personal result ≠ guaranteed outcome for everyone—always clarify this.',
          'Start with "My own experience was..."; avoid medical claims and guaranteed results.',
          'Use only language your company has officially approved.',
        ],
      },
      {
        id: 'ue3',
        baslik: 'Digital Posts & Declarations: Quick Check',
        emoji: '📲',
        sure: '6 min',
        seviye: 'Basic',
        ozet: 'Stay safe on your profile, stories, and messages—key reminders for income, health, and data.',
        maddeler: [
          'Income: "X earnings in Y time" carries both trust and compliance risk—use measured language.',
          'Health: start with "My own experience was..."; avoid medical claims and guarantees.',
          'Data privacy: don\'t share personal data without permission; no unnecessary list transfers.',
          'Distance selling: accurately explain your company\'s order and withdrawal processes.',
          'Transparent, measured, compliance-aligned language → long-term trust.',
        ],
      },
    ],
  },
  {
    id: 'urun',
    baslik: 'Product & Company',
    emoji: '🏢',
    renk: 'bg-[#FAF5FF] dark:bg-[#1a0030] text-[#6B21A8] dark:text-[#d8b4fe] border-[#E9D5FF] dark:border-[#6b21a830]',
    konular: [
      {
        id: 'us1',
        baslik: 'From Doubt to Belief: A Distributor\'s Product Story',
        emoji: '✨',
        sure: '8 min',
        seviye: 'Medium',
        ozet: 'Building this business without believing in the products is both unsustainable and unethical.',
        maddeler: [
          'Building this business without believing in the products is both unsustainable and unethical.',
          'Use the product yourself and with your family; take notes on results for 30 days.',
          '"Here\'s what I personally noticed—your experience may differ" is story, not script.',
          'Product experience replaces sales technique; your story reduces reliance on scripts.',
          'Ethical belief in what you sell = sustainable business.',
        ],
      },
      {
        id: 'us2',
        baslik: 'Knowing Your Company: The Foundation of Trust',
        emoji: '🔬',
        sure: '7 min',
        seviye: 'Basic',
        ozet: 'Prospects direct trust questions to the company—being able to answer builds your credibility.',
        maddeler: [
          'Prospects direct trust concerns to the company—answering those questions builds credibility.',
          '5 areas to know: founding history, product portfolio, legal registrations, compensation plan transparency, support infrastructure.',
          'Direct candidates to primary sources: "Look here—it\'s on this page."',
          'Read independent reviews; don\'t rely only on what the company tells you.',
          'Informed distributor = trustworthy distributor.',
        ],
      },
    ],
  },
]

export function getTrainingData(lang: 'tr' | 'en'): Kategori[] {
  return lang === 'en' ? EN_KATEGORILER : TR_KATEGORILER
}
